# Generated by Django 2.1.8 on 2019-05-12 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letter',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='user',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_from',
            field=models.ForeignKey(default='알수없음', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='letter_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
