# Generated by Django 2.1.8 on 2019-05-12 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190512_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='public',
        ),
    ]
