# Generated by Django 2.1.8 on 2019-05-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_letter_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='static/default_image.png', null=True, upload_to='profile_images'),
        ),
    ]
