# Generated by Django 2.1.8 on 2019-05-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190513_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='Hongik_festival/festival/users/static/default_image.png', null=True, upload_to='profile_images'),
        ),
    ]
